version: '3'

services:
  db:
    image: postgres:14-alpine3.17
    container_name: db_app
    environment:
      - POSTGRES_PASSWORD=password
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  redis:
    image: redis:latest
    container_name: redis_app
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - ./data/cache:/data

  celery:
    build:
      context: .
      dockerfile: docker_celery/Dockerfile
    command: celery -A Coursework_8_DRF_Docker worker -l info
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  app:
    build:
      context: .
      dockerfile: docker_django/Dockerfile
    network_mode: host
    image: app
    container_name: drf
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: python manage.py runserver 0.0.0.0:8000
